apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: install-ovirt-demo
spec:
  name: ovirt-operator
  complianceType: musthave
  operatorGroup:
    name: openshift-cnv-op
    namespace: openshift-cnv
    targetNamespaces:
      - openshift-cnv
  remediationAction: enforce
  severity: critical
  subscription:
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  upgradeApproval: None
