apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-openshift-gitops
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      userx: "cstark"
  remediationAction: enforce
policies:
  #  - name: install-gitops-cstark
   #   manifests:
   #     - path: openshift-gitops-subscription.yaml
   # - name: config-namespace-cstark
    #  manifests:
    #    - path: config-namespaces.yaml  
  - name: simplevm
    manifests:
      - path: simplevm.yaml
  - name: hyperconverged
    manifests:
      - path: hyperconverged.yaml       
